### ISSUE TITLE
About Branch

### ISSUE THREAD

**Issue by kiran-first** [Azure-DevOps-October/Azure-GitRepo#7]
In this repositary there is not showing any option to create new branch .. only filter branch option is showing

**Comment by rAZDevOps** [comment]
I can't create a branch. I want **permissions** to create branch.

**Comment by kbattiprolu88** [comment]
Please share your email-id's here so that I can help in giving access and the email id should be the registered email-id with github account

**Comment by rAZDevOps** [comment]
> Please share your email-id's here so that I can help in giving access and the email id should be the registered email-id with github account

rajuvisualpath.7@gmail.com
sivacloud1234@gmail.com
muralivisualpath10@gmail.com
afreenshaik66@gmail.com
wilsoncloud999@gmail.com

**Comment by kbattiprolu88** [comment]
@rAZDevOps  i have added all the above email id's and have provided write access to this git repository, kindly validate the access and let me know if you had any issues

**Comment by kiran-first** [comment]
> 

please add my email .. kirankumarnaidunare@gmail.com

**Comment by kiran-first** [comment]
add one more email... snehaazure521@gmail.com

**Comment by kbattiprolu88** [comment]
Git hub access has been given to all above email-id's and closing this issue
