### ISSUE TITLE
Github sync issue

### ISSUE THREAD

**Issue by afreen2612** [Azure-DevOps-October/Azure-GitRepo#8]
Created Documentation Folder on features-ashaik-858 branch but unable to see in Github repo oniline
![Git-documentation](https://user-images.githubusercontent.com/115777454/196931542-7d09257a-e9b8-42cf-8130-ff4cb35742ef.PNG)
![Git-online](https://user-images.githubusercontent.com/115777454/196931556-fe317292-1f39-4e25-9fef-15164b97140a.PNG)

**Comment by sivacloud1234** [comment]
Github Sync issue resolved.
